var Pokemon_Data = {
  p1: {
    name: "Bulbasaur",
    image: "https://pokestop.io/img/pokemon/bulbasaur-256x256.png",
    HitPoint: 45,
    Attack: 65,
    Defense: 65,
    Speed: 45,
  },
  p2: {
    name: "Alakazam",
    image: "https://pokestop.io/img/pokemon/alakazam-256x256.png",
    HitPoint: 55,
    Attack: 135,
    Defense: 95,
    Speed: 120,
  },
  p3: {
    name: "Charizard",
    image: "https://pokestop.io/img/pokemon/charizard-256x256.png",
    HitPoint: 78,
    Attack: 109,
    Defense: 85,
    Speed: 100,
  },
  p4: {
    name: "Pidgeotto",
    image: "https://pokestop.io/img/pokemon/pidgeotto-256x256.png",
    HitPoint: 63,
    Attack: 50,
    Defense: 50,
    Speed: 71,
  },
  p5: {
    name: "Arbok",
    image: "https://pokestop.io/img/pokemon/arbok-256x256.png",
    HitPoint: 50,
    Attack: 52,
    Defense: 67,
    Speed: 70,
  },
  p6: {
    name: "Nidorino",
    image: "https://pokestop.io/img/pokemon/nidorino-256x256.png",
    HitPoint: 61,
    Attack: 55,
    Defense: 57,
    Speed: 65,
  },
  p7: {
    name: "Ninetales",
    image: "https://pokestop.io/img/pokemon/ninetales-256x256.png",
    HitPoint: 73,
    Attack: 76,
    Defense: 75,
    Speed: 100,
  },
  p8: {
    name: "Jigglypuff",
    image: "https://pokestop.io/img/pokemon/jigglypuff-256x256.png",
    HitPoint: 115,
    Attack: 30,
    Defense: 20,
    Speed: 26,
  },
  p9: {
    name: "Rapidash",
    image: "https://pokestop.io/img/pokemon/rapidash-256x256.png",
    HitPoint: 50,
    Attack: 52,
    Defense: 67,
    Speed: 70,
  },
  p10: {
    name: "Wobbuffet",
    image: "https://pokestop.io/img/pokemon/wobbuffet-256x256.png",
    HitPoint: 51,
    Attack: 33,
    Defense: 58,
    Speed: 105,
  },
  p11: {
    name: "Magneton",
    image: "https://pokestop.io/img/pokemon/magneton-256x256.png",
    HitPoint: 50,
    Attack: 60,
    Defense: 95,
    Speed: 70,
  },
  p12: {
    name: "Goldeen",
    image: "https://pokestop.io/img/pokemon/goldeen-256x256.png",
    HitPoint: 45,
    Attack: 67,
    Defense: 60,
    Speed: 63,
  },
  p13: {
    name: "Electabuzz",
    image: "https://pokestop.io/img/pokemon/electabuzz-256x256.png",
    HitPoint: 65,
    Attack: 83,
    Defense: 57,
    Speed: 105,
  },
  p14: {
    name: "Azurill",
    image: "https://pokestop.io/img/pokemon/azurill-256x256.png",
    HitPoint: 50,
    Attack: 20,
    Defense: 40,
    Speed: 20,
  },
  p15: {
    name: "Blissey",
    image: "https://pokestop.io/img/pokemon/blissey-256x256.png",
    HitPoint: 255,
    Attack: 10,
    Defense: 10,
    Speed: 15,
  },
  p16: {
    name: "Scizor",
    image: "https://pokestop.io/img/pokemon/scizor-256x256.png",
    HitPoint: 70,
    Attack: 130,
    Defense: 100,
    Speed: 65,
  },
  p17: {
    name: "Umbreon",
    image: "https://pokestop.io/img/pokemon/umbreon-256x256.png",
    HitPoint: 95,
    Attack: 65,
    Defense: 110,
    Speed: 66,
  },
  p18: {
    name: "Hoppip",
    image: "https://pokestop.io/img/pokemon/hoppip-256x256.png",
    HitPoint: 35,
    Attack: 35,
    Defense: 40,
    Speed: 50,
  },
  p19: {
    name: "Lugia",
    image: "https://pokestop.io/img/pokemon/lugia-256x256.png",
    HitPoint: 106,
    Attack: 90,
    Defense: 130,
    Speed: 110,
  },
  p20: {
    name: "Sunflora",
    image: "https://pokestop.io/img/pokemon/sunflora-256x256.png",
    HitPoint: 75,
    Attack: 75,
    Defense: 55,
    Speed: 30,
  },
};
// On the top-right, the HP (hit points) next to the number 60
// indicates how much damage the Pokemon can take before being knocked out.
